language: java
dist: trusty
jdk:
  - oraclejdk8
before_install:
  - cd Backend && chmod +x gradlew
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
install:
  - ./gradlew clean build
after_success:
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Kotlin -r build/customJacocoReportDir/test/jacocoTestReport.xml
